[build]
  functions = "./functions"
  # Overrides UI settings.
  # builds gatsby and lambdas
  command = "yarn build"

[context.production]
  environment = { LAMBDA_ENV = "production", MEMBERS_LOG = "${{ secrets.MEMBERS_LOG }}" }

[context.deploy-preview.environment]
  # Naturally we would use NODE_ENV but this breaks the 
  # run-p command on yarn build within netlify deploy
  LAMBDA_ENV = "production"
  GATSBY_ENVIRONMENT = "preview"
